export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const STUDENT_LOADED = "STUDENT_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const USER_LOADED = "USER_LOADED";
export const LOADING = "LOADING";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL = "CREATE_PROFILE_FAIL";
export const SET_EDIT_MODE = "SET_EDIT_MODE";
export const CLEAR_EDIT_MODE = "CLEAR_EDIT_MODE";
export const SEND_DOCS = "SEND_DOCS";
export const SEND_DOCS_FAIL = "SEND_DOCS_FAIL";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const FILE_PATHS = "FILE_PATHS";
export const FILE_PATHS_ERROR = "FILE_PATHS_ERROR";
export const CREATE_RESUME = "CREATE_RESUME";
export const RESUME_DATA = "RESUME_DATA";
export const ERROR_FETCHING_RESUME_DATA = "ERROR_FETCHING_RESUME_DATA";
export const SENT_ADMIN_MESSAGE = "SENT_ADMIN_MESSAGE";
export const ERROR_SENT_ADMIN_MESSAGE = "ERROR_SENT_ADMIN_MESSAGE";
export const SUCCESS_PASSWORD_RESET_EMAIL_SENT = "SUCCESS_PASSWORD_RESET_EMAIL_SENT";
export const ERROR_SUCCESS_PASSWORD_RESET_EMAIL_NOT_SENT = "ERROR_SUCCESS_PASSWORD_RESET_EMAIL_NOT_SENT";
export const TOKEN_VERIFIED_PAYLOAD_RETURNED = "TOKEN_VERIFIED_PAYLOAD_RETURNED";
export const ERROR_VERIFYING_TOKEN = "ERROR_VERIFYING_TOKEN";
export const PASSWORD_SUCCESS_CHANGED_PAYLOAD = "PASSWORD_SUCCESS_CHANGED_PAYLOAD";

/* 
    @RULE: UTILITIES ACTION TYPES
*/

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";